GymTarget/Models/Trainees.cs
namespace GymTarget.Models
{
    public class Trainees
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string? Image { get; set; }

        public decimal PhoneNumber { get; set; }
        public string Gender { get; set; }
    }
}

GymTarget/Controllers/CoachesController.cs
using GymTarget.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace GymTarget.Controllers
{
    public class CoachesController : Controller
    {
        
            private readonly ApplicationDbContext _context;
            private readonly IWebHostEnvironment _webHostEnvironment;

        public CoachesController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
         {
                _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {

            var coache = _context.coaches.ToList();

            return View(coache);
        }

        [HttpGet]
        public IActionResult New()
        {
            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult New(Coaches coaches , IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string RootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string filename = Guid.NewGuid().ToString();
                    var Upload = Path.Combine(RootPath, @"Images\Products");
                    var ext = Path.GetExtension(file.FileName);

                    using (var filestream = new FileStream(Path.Combine(Upload, filename + ext), FileMode.Create))
                    {
                        file.CopyTo(filestream);
                    }
                    coaches.Image = @"Images\Products\" + filename + ext;
                }

                _context.coaches.Add(coaches);
                _context.SaveChanges();
                return RedirectToAction("Index");

            }

                return View(coaches);
            
        }


       


        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var item = _context.coaches.Find(Id);

            if (item == null)
            {
                return NotFound();
            }


            return View(item);
        }

        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Coaches coaches, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string RootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string filename = Guid.NewGuid().ToString();
                    var Upload = Path.Combine(RootPath, @"Images\Products");
                    var ext = Path.GetExtension(file.FileName);

                    using (var filestream = new FileStream(Path.Combine(Upload, filename + ext), FileMode.Create))
                    {
                        file.CopyTo(filestream);
                    }
                    coaches.Image = @"Images\Products\" + filename + ext;
                }

                _context.coaches.Update(coaches);
                _context.SaveChanges();
                return RedirectToAction("Index");

            }
            
                return View(coaches);
        }


        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var coache = _context.coaches.Find(id);

            if (coache == null)
            {
                return NotFound();
            }

            return View(coache);
        }
        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Deletecoaches(int? Id)

        {

            var coaches = _context.coaches.Find(Id);
            if (coaches == null)
            {
                return NotFound();
            }
            _context.Remove(coaches);
            _context.SaveChanges();

            return RedirectToAction("Index");

        }


    }
}

GymTarget/Controllers/TraineesController.cs
using GymTarget.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace GymTarget.Controllers
{
    public class TraineesController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public TraineesController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {

            var trainees = _context.Trainees.ToList();

            return View(trainees);
        }

        [HttpGet]
        public IActionResult New()
        {
            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult New(Trainees trainees, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string RootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string filename = Guid.NewGuid().ToString();
                    var Upload = Path.Combine(RootPath, @"Images\Products");
                    var ext = Path.GetExtension(file.FileName);

                    using (var filestream = new FileStream(Path.Combine(Upload, filename + ext), FileMode.Create))
                    {
                        file.CopyTo(filestream);
                    }
					trainees.Image = @"Images\Products\" + filename + ext;
                }

                _context.Trainees.Add(trainees);
                _context.SaveChanges();
                return RedirectToAction("Index");

            }

            return View(trainees);

        }





        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var item = _context.Trainees.Find(Id);

            if (item == null)
            {
                return NotFound();
            }


            return View(item);
        }

        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Trainees trainees, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string RootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string filename = Guid.NewGuid().ToString();
                    var Upload = Path.Combine(RootPath, @"Images\Products");
                    var ext = Path.GetExtension(file.FileName);

                    using (var filestream = new FileStream(Path.Combine(Upload, filename + ext), FileMode.Create))
                    {
                        file.CopyTo(filestream);
                    }
					trainees.Image = @"Images\Products\" + filename + ext;
                }

                _context.Trainees.Update(trainees);
                _context.SaveChanges();
                return RedirectToAction("Index");

            }

            return View(trainees);
        }


        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var trainees = _context.Trainees.Find(id);

            if (trainees == null)
            {
                return NotFound();
            }

            return View(trainees);
        }
        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Deletecoaches(int? Id)

        {

            var trainees = _context.Trainees.Find(Id);
            if (trainees == null)
            {
                return NotFound();
            }
            _context.Remove(trainees);
            _context.SaveChanges();

            return RedirectToAction("Index");

        }


    }
}

GymTarget/Views/Trainees/Delete.cshtml
@model Trainees

@{
    ViewData["Title"] = "Delete";
}
<div class="row">
    <div class="col-md-8">
        <form method="post" asp-action="Deletecoaches">
            <input asp-for="Id" hidden />

            <div class="border p-2 mt-4">
                <h2 class="text-primary">View Delete</h2>
                <hr />

                <div asp-validation-summary="All"></div>

                <div class="mb-2">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" disabled class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="mb-2">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" disabled class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>

                </div>


                <div class="form-group">
                    <label asp-for="Address"></label>
                    <input asp-for="Address" disabled class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>

                </div>


                <div class="mb-2">
                    <label asp-for="PhoneNumber"></label>
                    <input asp-for="PhoneNumber" disabled class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>

                </div>

                <div class="mb-1">
                    <label asp-for="Gender"></label>
                    <input asp-for="Gender" disabled class="form-control" />
                    <span asp-validation-for="Gender" class="text-danger"></span>

                </div>

                <div class="mb-2">
                    <br />
                    <hr />

                    <button type="submit" class="btn btn-primary" style="width:150px">Delete</button>
                    <a asp-action="Index" asp-controller="Student" class="btn btn-secondary" style="width:150px">
                        back to Student
                    </a>

                </div>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

GymTarget/Views/Trainees/Edit.cshtml
@model Trainees

@{
    ViewData["Title"] = "New";
}


<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">


            <div asp-validation-summary="All"></div>

            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>

            </div>

            <div class="form-group">
                <label asp-for="Address"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>

            </div>




            <div class="form-group">
                <label asp-for="PhoneNumber"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Gender"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>

            </div>

            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input type="file" name="file" id="imgfile" class="form-control" onchange="fillimg(event);" />
            </div>


            <br />
            <hr />

            <button type="submit" class="btn btn-primary" style="width:150px">Save</button>
            <a asp-action="Index" asp-controller="Coaches" class="btn btn-secondary" style="width:150px">
                back to Coache
            </a>

        </form>

    </div>

    <div class="col-md-4">
        <div class="container">
            <img id="ImagePrevew" src="~/@Model.Image" width="300" height="300" />
        </div>
    </div>




</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        var fillimg = function (event) {
            var imgholder = document.getElementById("ImagePrevew");
            imgholder.src = URL.createObjectURL(event.target.files[0]);
        }
    </script>

}

GymTarget/Views/Trainees/Index.cshtml
@model List<Trainees>


<div class="container p-4">

@* 	<partial name="Silder" />
 *@	<div class="row">

		<div class="col-6">
			<h2 class="text-primary">Trainees View</h2>
		</div>

		<div class="col-6  pb-3 text-end">
			<a asp-action="New" class="btn btn-primary">
				<i class="bi bi-plus-circle-dotted"></i> &nbsp; Add New Trainees

			</a>
		</div>

		<table class="table table-border table-hover">

			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Address</th>
				<th>PhoneNumber</th>
				<th>Gender</th>
				<th>Events</th>
			</tr>

			@foreach (var item in Model)
			{
				<tr>
					<td width="20%">@item.Name</td>
					<td width="20%">@item.Email</td>
					<td width="20%">@item.Address</td>
					<td width="20%">@item.PhoneNumber</td>
					<td width="10%">@item.Gender</td>
					<td width="20%">
						<a asp-controller="Trainees" asp-action="Edit" asp-route-Id="@item.Id" class="btn btn-sm btn-primary">
							<i class="bi bi-pencil"></i>
						</a>
						&nbsp;
						<a asp-controller="Trainees" asp-action="Delete" asp-route-Id="@item.Id" class="btn btn-sm btn-danger">
							<i class="bi bi-trash3"></i>
						</a>
					</td>
				</tr>

			}


		</table>



	</div>
@* 		<partial name="Silder_2" />
 *@


</div>

GymTarget/Views/Trainees/New.cshtml
@model Trainees

@{
    ViewData["Title"] = "New";
}


<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div class="row pb-2">

                <h2 class="text-primary">Add New Coaches</h2>
                <hr />

            </div>

            <div asp-validation-summary="All"></div>

            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>

            </div>

            <div class="form-group">
                <label asp-for="Address"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>

            </div>




            <div class="form-group">
                <label asp-for="PhoneNumber"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Gender"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>

            </div>

            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input type="file" name="file" id="imgfile" class="form-control" onchange="fillimg(event);" />
            </div>


            <br />
            <hr />

            <button type="submit" class="btn btn-primary" style="width:150px">Save</button>
            <a asp-action="Index" asp-controller="Coaches" class="btn btn-secondary" style="width:150px">
                back to Coache
            </a>

        </form>

    </div>

    <div class="col-md-4">
        <div class="container">
            <img id="ImagePrevew" width="300" height="300" />
        </div>
    </div>




</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        var fillimg = function(event){
            var imgholder = document.getElementById("ImagePrevew");
            imgholder.src = URL.createObjectURL(event.target.files[0]);
        }
    </script>

}